name: Validate Renovate Config

on:
  pull_request: {}
  push:
    branches:
      - renovate/reconfigure

permissions:
  contents: read

jobs:
  validate-renovate-config:
    name: Validate renovate config
    runs-on: ubuntu-latest
    container:
      image: renovate/renovate:44.46.4@sha256:3b64619da15eec8cc7eb7e422698736d6e129bf0832e8b90fe956706cde3c133
      options: --user root
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - run: renovate --version
      - run: renovate-config-validator .github/renovate.json5
